version: '3.5'

services:
  uikit-seed-cnj-jus-br:
    image: ${DOCKER_REGISTRY}uikit-seed.cnj.jus.br:${BRANCH}.${VERSION}
    ports:
      - "80:80"
      - "443:443"
    environment:
      AUTH_AUTHORITY: 'https://sso.cloud.pje.jus.br/auth/realms/pje/'
      AUTH_CLIENT_ID: 'sistema'
      AUTH_SCOPE: 'openid profile email roles offline_access'
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.01'
          memory: 16M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 120s
    labels:
      kompose.service.expose: uikit-seed.cnj.jus.br

networks:
  default:
    name: ns-uikit-seed
