version: '3.5'

services:
  uikit-seed-cnj-jus-br:
    image: ${DOCKER_REGISTRY}uikit-seed.cnj.jus.br:${BRANCH:-develop}.${VERSION}-debug
    ports:
      - "80:4200"
    environment:
      AUTH_AUTHORITY: 'https://sso.stg.cloud.pje.jus.br/auth/realms/pje/'
      AUTH_CLIENT_ID: 'sistema'
      AUTH_SCOPE: 'openid profile email roles offline_access'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.6'
          memory: 2048M
        reservations:
          cpus: '0.2'
          memory: 768M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 120s
    labels:
      kompose.service.expose: uikit-seed-${BRANCH_DNS:-develop}-alpha.stg.cnj.cloud

networks:
  default:
    name: ns-uikit-seed-${BRANCH_DNS:-develop}-alpha
